mysql:
  host: "localhost"
  port: 3306
  database: "crewards_db"
  username: "root"
  password: ""

npc:
  name: "&6&lRECOMPENSAS"

menu:
  title: "Menu de Recompensas"
  rows: 4

messages:
  no_perm: "&cVocê não tem permissão para coletar isto"
  in_cooldown: "&4&lOOOPS! &cVocê precisa esperar {cooldown} para coletar novamente"

item_to_remove: "DIAMOND_SWORD" # permissão 'reward.op' double left click para remover o NPC

rewards:
  reward1:
    slot: 1
    name: "&aDiamante Diário"
    item: "ENDER_CHEST"
    lore:
      - "&7Você pode coletar um diamante diário"
      - "&7A cada 1 hora você pode coletar um diamante"
      - " "
    lore_ready: "&bClique para coletar"
    lore_in_cooldown: "&cVocê precisa esperar {cooldown} para coletar isto"
    lore_no_permission: "&cVocê não tem permissão para coletar isto"
    permission: "rewards.reward1"
    cooldown: 36000
    message: "&aVocê recebeu o diamante!"
    commands:
      - "give {player} diamond 1"
      - "say {player} coletou a recompensa: {reward}"

  reward2:
    slot: 4
    name: "&cItem Semanal"
    item: "CACTUS"
    lore:
      - "&7Você pode coletar um item diário"
      - "&7A cada 3 horas você pode coletar um item"
      - ""
    lore_ready: "&bClique para coletar"
    lore_in_cooldown: "&cVocê precisa esperar {cooldown} para coletar isto"
    lore_no_permission: "&cVocê não tem permissão para coletar isto"
    permission: "rewards.reward2"
    cooldown: 3600
    message: "&aVocê recebeu o item!"
    commands:
      - "give {player} diamond_sword"
      - "say {player} coletou a recompensa: {reward}"

  vip:
    slot: 7
    name: "&aRecompensa VIP++"
    item: "ENDER_PEARL"
    lore:
      - "&7Recompensa VIP++"
      - "&7Disponível a cada 6 horas"
      - ""
      - "&eDisponível para jogadores VIP"
      - ""
    lore_ready: "&bClique para coletar"
    lore_in_cooldown: "&cVocê precisa esperar {cooldown} para coletar isto"
    lore_no_permission: "&cVocê não tem permissão para coletar isto"
    permission: "rewards.vip2"
    cooldown: 180
    message: "&aVocê recebeu a recompensa VIP!"
    commands:
      - "give {player} diamond 50"
      - "say {player} coletou a recompensa: {reward}"
